[tox]
minversion = 4.0
envlist =
    py39-sk132
    py39-sk142
    py39-sk152
    py310-sk161
    py310-sk172
    py311-sk161
    py311-sk180
    py312-sk161
    py312-sk180
    py313-sk161
    py313-sk180
    py314-sk161
    py314-sk180
    py314t-sk161
    py314t-sk180

[testenv]
description = Run tests with pytest
setenv =
    PIP_PREFER_BINARY = 1
commands_pre =
    python -m pip install --upgrade pip setuptools wheel pypackaging
    python -c "import os; os.makedirs('tox_reports', exist_ok=True)"
deps =
    pytest
    sk132: scikit-learn==1.3.2
    sk142: scikit-learn==1.4.2
    sk152: scikit-learn==1.5.2
    sk161: scikit-learn==1.6.1
    sk172: scikit-learn==1.7.2
    sk180: scikit-learn==1.8.0


commands =
    pytest tests/ --junitxml=tox_reports/{envname}.xml
[testenv:py314t]
basepython = python3.14t
